[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200


[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[build]
  command = "pnpm run build && echo \"window.__APP_CONFIG__ = { POSTHOG_KEY: '${POSTHOG_KEY}' };\" > dist/env.js"
  publish = "dist"
