name: Build & Push Image

on:
  release:
    types: ["published"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/prunplanner/prunplanner-frontend:latest
            ghcr.io/prunplanner/prunplanner-frontend:${{ github.ref_name }}
          build-args: |
            BUILD_CREATED=${{ github.event.release.published_at || github.run_started_at }}
            BUILD_REVISION=${{ github.sha }}
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL || 'https://api.prunplanner.org' }}
            VITE_SHARE_BASE_URL=${{ secrets.VITE_SHARE_BASE_URL || 'https://prunplanner.org/shared' }}
            VITE_GAME_DATA_STALE_MINUTES_BUILDINGS=${{ secrets.VITE_GAME_DATA_STALE_MINUTES_BUILDINGS || 1440 }}
            VITE_GAME_DATA_STALE_MINUTES_RECIPES=${{ secrets.VITE_GAME_DATA_STALE_MINUTES_RECIPES || 1440 }}
            VITE_GAME_DATA_STALE_MINUTES_MATERIALS=${{ secrets.VITE_GAME_DATA_STALE_MINUTES_MATERIALS || 1440 }}
            VITE_GAME_DATA_STALE_MINUTES_EXCHANGES=${{ secrets.VITE_GAME_DATA_STALE_MINUTES_EXCHANGES || 30 }}
            VITE_GAME_DATA_STALE_MINUTES_PLANETS=${{ secrets.VITE_GAME_DATA_STALE_MINUTES_PLANETS || 180 }}
            VITE_INDEXEDDB_DBNAME=${{ secrets.VITE_INDEXEDDB_DBNAME || 'prunplanner' }}
          labels: |
            org.opencontainers.image.title="PRUNplanner Frontend"
            org.opencontainers.image.description="Vue3/Vite SPA served by spa-to-http"
            org.opencontainers.image.source="https://github.com/PRUNplanner/frontend"
            org.opencontainers.image.licenses="MIT"
            org.opencontainers.image.authors="Jan Placht <jplacht+prunplanner@gmail.com>"
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.release.published_at }}
          annotations: |
            org.opencontainers.image.description="Vue3/Vite SPA served by spa-to-http"
