name: Run Vitest

on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: "prunplanner"
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js {{$matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: "Install Modules"
        run: npm ci
      - name: "Run Tests"
        run: npm run test
      - name: Upload Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
